FROM --platform=linux/amd64 fedora

RUN yum install rpm-build -y

ADD . /repo
WORKDIR /repo
RUN ./autogen.sh sysdeps --install
RUN tito build --rpm --test
RUN ./autogen.sh
RUN ./configure
RUN make -j8
